### ISSUE TITLE
PSR-7 ?

### ISSUE THREAD

**Issue by harikt** [fol-project/http#1]
Hi, 

I noticed you referencing the post by mwop. Wonder why you didn't addded PSR-7 http-message interface as a dependency to composer.json .

PS : Your work on the Embed brings me to here. Good work on it.

Thank you.

**Comment by oscarotero** [comment]
Hello!
Yes, I've planned to add PSR-7 support to this library, in fact, there is a branch for this. But the http-message interface has changed recently and I have to update my implementation.
Anyway, I don't know if release a psr-7 based version while the http-message interface is not stable enought.

:smile:

**Comment by harikt** [comment]
Thanks @oscarotero .
I will close the issue for you are aware of the same. Just wanted to communicate.

Thanks once again for being quick.
